### ISSUE TITLE
disabling rootwait; `root=` is invalid.

### ISSUE THREAD

**Issue by Yash-Garg** [nix-community/raspberry-pi-nix#30]
I get this error while trying to build an `sdImage`, setting `boot.initrd.systemd.enableTpm2 = lib.mkForce false;` works but just confirming if this is expected? 

Also, for some reason the built `sdImage` doesn't boot for me on Raspberry Pi 5. 
[Config](https://github.com/Yash-Garg/dotfiles/blob/feat/raspi5/systems/aarch64-linux/eclipse/default.nix)

```nix
Disabling rootwait; root= is invalid.
/dev/root: Can't open blockdev
```

**Comment by bddvlpr** [comment]
I'm still getting root=fstab is invalid. How did you resolve this?

**Comment by Yash-Garg** [comment]
> I'm still getting root=fstab is invalid. How did you resolve this?

In my case it was due to a `mixin` I was using from [srvos](https://nix-community.github.io/srvos/nixos/type/#server-nixosmodulesserver), removing that fixed it for me, [`hardware-configuration.nix`](https://github.com/Yash-Garg/dotfiles/blob/stable/systems/aarch64-linux/cosmos/hardware-configuration.nix) is here for reference.

**Comment by bddvlpr** [comment]
I ended up just disabling systemd on initrd like so; `boot.initrd.systemd.enable = false;` so I could keep the srvos module.
