### ISSUE TITLE
Uboot is built even if uboot is disabled

### ISSUE THREAD

**Issue by tnichols217** [nix-community/raspberry-pi-nix#41]
The multiple usages of `builtins.toString pkgs.uboot-rpi-arm64` within [default.nix](https://github.com/nix-community/raspberry-pi-nix/blob/master/rpi/default.nix) requires nix to build the uboot package even if uboot is disabled.

I'm unsure if this is an intentional decision based on the requirements of this script, but I would recommend making conditionals for uboot related sections of the script to not be included if uboot is disabled

**Comment by tstat** [comment]
Yes, good thought. It wasn't intentional, just an oversight.
