### ISSUE TITLE
Kernel caching in README

### ISSUE THREAD

**Issue by nbrr** [nix-community/raspberry-pi-nix#53]
[This bit of the README](https://github.com/nix-community/raspberry-pi-nix/commit/4ecdee4572eed2c2be13908bc8fbd8a7a8b3d7ec#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L29-L34) was removed, yet the current README [still references to it](https://github.com/nix-community/raspberry-pi-nix/blob/master/README.md?plain=1#L95).

```nix
  nixConfig = {
    extra-substituters = [ "https://raspberry-pi-nix.cachix.org" ];
    extra-trusted-public-keys = [
      "raspberry-pi-nix.cachix.org-1:WmV2rdSangxW0rZjY/tBvBDSaNFQ3DyEQsVw8EvHn9o="
    ];
  };
```

What is the current way of benefiting from a cache?

FWIW this seems to be doing fine:
```nix
    extra-substituters = [ "https://nix-community.cachix.org" ];
    extra-trusted-public-keys = [
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
```

**Comment by tstat** [comment]
Oh yes, that's a mistake. The nix-community cache is the current cache.

**Comment by tobiasBora** [comment]
Do we still need kernel caching now that rpi5 is in nixpkgs ? https://github.com/NixOS/nixos-hardware/pull/927

**Comment by mroi** [comment]
@tobiasBora The PR your referenced seems to add rpi5 support to [nixos-hardware](https://github.com/NixOS/nixos-hardware), not Nixpkgs. Is there some automatic process by which this addition would move into Nixpkgs?

**Comment by tstat** [comment]
@tobiasBora as things are written we do, since we have our own derivation of the rpi linux fork. I assume you are more getting at "can we avoid defining a kernel derivation in this repo now", and yes, we probably could. I don't really think we should though. I like being able to bump the dep more aggressively, have control over things like the kernel config and patches, etc.

**Comment by tobiasBora** [comment]
Ok thanks for your answer @tstat ! Regarding @mroi 's question, you are right, I actually realized that it is in nixos hardware, not nixpkgs directly… hence it is not cached by Hydra itself, sorry.

**Comment by mroi** [comment]
Got it. Thanks to you both for the clarification.

**Comment by tstat** [comment]
90ff6a72a9f2e287c6890fbf6cbe60fde5115844
