### ISSUE TITLE
How to Install Custom dts/dtbo?

### ISSUE THREAD

**Issue by hftsai256** [nix-community/raspberry-pi-nix#76]
I'm seeking a way to build a Raspberry Pi CM4 image with several customized dts/dtbo, e.g. [mcp4728.dts](https://gist.github.com/hftsai256/6e8c3111649b48d06df6e703caaaa71d#file-mcp4728-dts). My first intuition is something like this:
```
hardware.deviceTree = {
  kernelPackage = pkgs.linux_rpi4;
  filter = "bcm2711-rpi-cm4.dtb";
  overlays = [
    { name = "mcp4728"; dtsFile = ./mcp4728.dts; }
    { name = "spi6-1cs"; dtboFile = "${pkgs.device-tree_rpi.overlays}/spi6-1cs.dtbo"; }
  ];
};
```
But then I find `boot.loader.generic-extlinux-compatible.useGenerationDeviceTree = false`, and I doubt the path I'm taking will be effective.

My another thought is to create a separate Nix package to handle the build/install part:
```
{ stdenvNoCC, dtc }:
stdenvNoCC.mkDerivation {
  pname = "dtoverlays";
  version = "0.0.1";
  src = ./.;
  buildInputs = [ dtc ];
  installPhase = ''
    install -d $out/boot/firmware/overlays
    mv build/*.dtbo $out/boot/firmware/overlays
  '';
}
```
However as far as I concerned, the install path `/boot/firmware/overlays` is in a different partition from `rootfs`, and therefore I also doubt that I can include this package in `environment.systemPackages`

 Is there a way to build the dtbo from source and install them into `/boot/firmware/overlays`?

**Comment by tstat** [comment]
Hey @hftsai256. The short answer to your question is that overlays are taken from the package `raspberrypifw`, so you could override that to add an overlay. This is mentioned in the readme under [this section](https://github.com/nix-community/raspberry-pi-nix?tab=readme-ov-file#firmware-partition-implementation-notes).

Reading the firmware populating script might clarify how this all fits together in your mind. Specifically, the device tree overlays are populated [here](https://github.com/nix-community/raspberry-pi-nix/blob/master/rpi/default.nix#L159-L181).
